sdxl:
    class: StableDiffusionXLInpaintPipeline
    checkpoint: SG161222/RealVisXL_V2.0
    torch_dtype: fp32
    use_safetensors: True

kandi21:
    class: AutoPipelineForInpainting
    checkpoint: kandinsky-community/kandinsky-2-1-inpaint
    torch_dtype: fp16
    use_safetensors: True